//
//  CountryCodes.swift
//  HangryDraft
//
//  Created by Simone Grant on 11/9/17.
//  Copyright © 2017 Simone Grant. All rights reserved.
//

import Foundation

struct CountryInfo {
    var country: String
    var shortAbbreviation: String
    var longAbbreviation: String
    var callCode: String
}

class Countries {
    
    class var allCountries: [CountryInfo] {
        
        get {
            return [
                CountryInfo(country: "Afghanistan", shortAbbreviation: "AF", longAbbreviation: "AFG", callCode: "+93"),
                CountryInfo(country: "Åland Islands", shortAbbreviation: "AX", longAbbreviation: "ALA", callCode: "+358"),
                CountryInfo(country: "Albania", shortAbbreviation: "AL", longAbbreviation: "ALB", callCode: "+355"),
                CountryInfo(country: "Algeria", shortAbbreviation: "DZ", longAbbreviation: "DZA", callCode: "+213"),
                CountryInfo(country: "American Samoa", shortAbbreviation: "AS", longAbbreviation: "ASM", callCode: "+684"),
                CountryInfo(country: "Andorra", shortAbbreviation: "AD", longAbbreviation: "AND", callCode: "+376"),
                CountryInfo(country: "Angola", shortAbbreviation: "AO", longAbbreviation: "AGO", callCode: "+244"),
                CountryInfo(country: "Anguilla", shortAbbreviation: "AI", longAbbreviation: "AIA", callCode: "+264"),
                CountryInfo(country: "Antarctica", shortAbbreviation: "AQ", longAbbreviation: "ATA", callCode: "+672"),
                CountryInfo(country: "Antigua and Barbuda", shortAbbreviation: "AG", longAbbreviation: "ATG", callCode: "+268"),
                CountryInfo(country: "Argentina", shortAbbreviation: "AR", longAbbreviation: "ARG", callCode: "+54"),
                CountryInfo(country: "Armenia", shortAbbreviation: "AM", longAbbreviation: "ARM", callCode: "+374"),
                CountryInfo(country: "Aruba", shortAbbreviation: "AW", longAbbreviation: "ABW", callCode: "+297"),
                CountryInfo(country: "Australia", shortAbbreviation: "AU", longAbbreviation: "AUS", callCode: "+61"),
                CountryInfo(country: "Austria", shortAbbreviation: "AT", longAbbreviation: "AUT", callCode: "+43"),
                CountryInfo(country: "Azerbaijan", shortAbbreviation: "AZ", longAbbreviation: "AZE", callCode: "+994"),
                CountryInfo(country: "Bahamas", shortAbbreviation: "BS", longAbbreviation: "BHS", callCode: "+242"),
                CountryInfo(country: "Bahrain", shortAbbreviation: "BH", longAbbreviation: "BHR", callCode: "+973"),
                CountryInfo(country: "Bangladesh", shortAbbreviation: "BD", longAbbreviation: "BGD", callCode: "+880"),
                CountryInfo(country: "Barbados", shortAbbreviation: "BB", longAbbreviation: "BRB", callCode: "+246"),
                CountryInfo(country: "Belarus", shortAbbreviation: "BY", longAbbreviation: "BLR", callCode: "+375"),
                CountryInfo(country: "Belgium", shortAbbreviation: "BE", longAbbreviation: "BEL", callCode: "+32"),
                CountryInfo(country: "Belize", shortAbbreviation: "BZ", longAbbreviation: "BLZ", callCode: "+501"),
                CountryInfo(country: "Benin", shortAbbreviation: "BJ", longAbbreviation: "BEN", callCode: "+229"),
                CountryInfo(country: "Bermuda", shortAbbreviation: "BM", longAbbreviation: "BMU", callCode: "+441"),
                CountryInfo(country: "Bhutan", shortAbbreviation: "BT", longAbbreviation: "BTN", callCode: "+975"),
                CountryInfo(country: "Bolivia, Plurinational State of", shortAbbreviation: "BO", longAbbreviation: "BOL", callCode: "+591"),
                CountryInfo(country: "Bonaire, Sint Eustatius and Saba", shortAbbreviation: "BQ", longAbbreviation: "BES", callCode: "+599"),
                CountryInfo(country: "Bosnia and Herzegovina", shortAbbreviation: "BA", longAbbreviation: "BIH", callCode: "+387"),
                CountryInfo(country: "Botswana", shortAbbreviation: "BW", longAbbreviation: "BWA", callCode: "+267"),
                CountryInfo(country: "Bouvet Island", shortAbbreviation: "BV", longAbbreviation: "BVT", callCode: "+47"),
                CountryInfo(country: "Brazil", shortAbbreviation: "BR", longAbbreviation: "BRA", callCode: "+55"),
                CountryInfo(country: "British Indian Ocean Territory", shortAbbreviation: "IO", longAbbreviation: "IOT", callCode: "+246"),
                CountryInfo(country: "Brunei Darussalam", shortAbbreviation: "BN", longAbbreviation: "BRN", callCode: "+673"),
                CountryInfo(country: "Bulgaria", shortAbbreviation: "BG", longAbbreviation: "BGR", callCode: "+359"),
                CountryInfo(country: "Burkina Faso", shortAbbreviation: "BF", longAbbreviation: "BFA", callCode: "+226"),
                CountryInfo(country: "Burundi", shortAbbreviation: "BI", longAbbreviation: "BDI", callCode: "+257"),
                CountryInfo(country: "Cambodia", shortAbbreviation: "KH", longAbbreviation: "KHM", callCode: "+855"),
                CountryInfo(country: "Cameroon", shortAbbreviation: "CM", longAbbreviation: "CMR", callCode: "+237"),
                CountryInfo(country: "Canada", shortAbbreviation: "CA", longAbbreviation: "CAN", callCode: "+1"),
                CountryInfo(country: "Cabo Verde", shortAbbreviation: "CV", longAbbreviation: "CPV", callCode: "+238"),
                CountryInfo(country: "Cayman Islands", shortAbbreviation: "KY", longAbbreviation: "CYM", callCode: "+345"),
                CountryInfo(country: "Central African Republic", shortAbbreviation: "CF", longAbbreviation: "CAF", callCode: "+236"),
                CountryInfo(country: "Chad", shortAbbreviation: "TD", longAbbreviation: "TCD", callCode: "+235"),
                CountryInfo(country: "Chile", shortAbbreviation: "CL", longAbbreviation: "CHL", callCode: "+56"),
                CountryInfo(country: "China", shortAbbreviation: "CN", longAbbreviation: "CHN", callCode: "+86"),
                CountryInfo(country: "Christmas Island", shortAbbreviation: "CX", longAbbreviation: "CXR", callCode: "+61"),
                CountryInfo(country: "Cocos (Keeling) Islands", shortAbbreviation: "CC", longAbbreviation: "CCK", callCode: "+891"),
                CountryInfo(country: "Colombia", shortAbbreviation: "CO", longAbbreviation: "COL", callCode: "+57"),
                CountryInfo(country: "Comoros", shortAbbreviation: "KM", longAbbreviation: "COM", callCode: "+269"),
                CountryInfo(country: "Congo", shortAbbreviation: "CG", longAbbreviation: "COG", callCode: "+242"),
                CountryInfo(country: "Congo, the Democratic Republic of the", shortAbbreviation: "CD", longAbbreviation: "COD", callCode: "+243"),
                CountryInfo(country: "Cook Islands", shortAbbreviation: "CK", longAbbreviation: "COK", callCode: "+682"),
                CountryInfo(country: "Costa Rica", shortAbbreviation: "CR", longAbbreviation: "CRI", callCode: "+506"),
                CountryInfo(country: "Côte d'Ivoire", shortAbbreviation: "CI", longAbbreviation: "CIV", callCode: "+225"),
                CountryInfo(country: "Croatia", shortAbbreviation: "HR", longAbbreviation: "HRV", callCode: "+385"),
                CountryInfo(country: "Cuba", shortAbbreviation: "CU", longAbbreviation: "CUB", callCode: "+53"),
                CountryInfo(country: "Curaçao", shortAbbreviation: "CW", longAbbreviation: "CUW", callCode: "+599"),
                CountryInfo(country: "Cyprus", shortAbbreviation: "CY", longAbbreviation: "CYP", callCode: "+357"),
                CountryInfo(country: "Czech Republic", shortAbbreviation: "CZ", longAbbreviation: "CZE", callCode: "+420"),
                CountryInfo(country: "Denmark", shortAbbreviation: "DK", longAbbreviation: "DNK", callCode: "+45"),
                CountryInfo(country: "Djibouti", shortAbbreviation: "DJ", longAbbreviation: "DJI", callCode: "+253"),
                CountryInfo(country: "Dominica", shortAbbreviation: "DM", longAbbreviation: "DMA", callCode: "+767"),
                CountryInfo(country: "Dominican Republic", shortAbbreviation: "DO", longAbbreviation: "DOM", callCode: "+809"),
                CountryInfo(country: "Ecuador", shortAbbreviation: "EC", longAbbreviation: "ECU", callCode: "+593"),
                CountryInfo(country: "Egypt", shortAbbreviation: "EG", longAbbreviation: "EGY", callCode: "+20"),
                CountryInfo(country: "El Salvador", shortAbbreviation: "SV", longAbbreviation: "SLV", callCode: "+503"),
                CountryInfo(country: "Equatorial Guinea", shortAbbreviation: "GQ", longAbbreviation: "GNQ", callCode: "+240"),
                CountryInfo(country: "Eritrea", shortAbbreviation: "ER", longAbbreviation: "ERI", callCode: "+291"),
                CountryInfo(country: "Estonia", shortAbbreviation: "EE", longAbbreviation: "EST", callCode: "+372"),
                CountryInfo(country: "Ethiopia", shortAbbreviation: "ET", longAbbreviation: "ETH", callCode: "+251"),
                CountryInfo(country: "Falkland Islands (Malvinas)", shortAbbreviation: "FK", longAbbreviation: "FLK", callCode: "+500"),
                CountryInfo(country: "Faroe Islands", shortAbbreviation: "FO", longAbbreviation: "FRO", callCode: "+298"),
                CountryInfo(country: "Fiji", shortAbbreviation: "FJ", longAbbreviation: "FJI", callCode: "+679"),
                CountryInfo(country: "Finland", shortAbbreviation: "FI", longAbbreviation: "FIN", callCode: "+358"),
                CountryInfo(country: "France", shortAbbreviation: "FR", longAbbreviation: "FRA", callCode: "+33"),
                CountryInfo(country: "French Guiana", shortAbbreviation: "GF", longAbbreviation: "GUF", callCode: "+594"),
                CountryInfo(country: "French Polynesia", shortAbbreviation: "PF", longAbbreviation: "PYF", callCode: "+689"),
                CountryInfo(country: "French Southern Territories", shortAbbreviation: "TF", longAbbreviation: "ATF", callCode: "+689"),
                CountryInfo(country: "Gabon", shortAbbreviation: "GA", longAbbreviation: "GAB", callCode: "+241"),
                CountryInfo(country: "Gambia", shortAbbreviation: "GM", longAbbreviation: "GMB", callCode: "+220"),
                CountryInfo(country: "Georgia", shortAbbreviation: "GE", longAbbreviation: "GEO", callCode: "+995"),
                CountryInfo(country: "Germany", shortAbbreviation: "DE", longAbbreviation: "DEU", callCode: "+49"),
                CountryInfo(country: "Ghana", shortAbbreviation: "GH", longAbbreviation: "GHA", callCode: "+233"),
                CountryInfo(country: "Gibraltar", shortAbbreviation: "GI", longAbbreviation: "GIB", callCode: "+350"),
                CountryInfo(country: "Greece", shortAbbreviation: "GR", longAbbreviation: "GRC", callCode: "+30"),
                CountryInfo(country: "Greenland", shortAbbreviation: "GL", longAbbreviation: "GRL", callCode: "+299"),
                CountryInfo(country: "Grenada", shortAbbreviation: "GD", longAbbreviation: "GRD", callCode: "+473"),
                CountryInfo(country: "Guadeloupe", shortAbbreviation: "GP", longAbbreviation: "GLP", callCode: "+590"),
                CountryInfo(country: "Guam", shortAbbreviation: "GU", longAbbreviation: "GUM", callCode: "+671"),
                CountryInfo(country: "Guatemala", shortAbbreviation: "GT", longAbbreviation: "GTM", callCode: "+502"),
                CountryInfo(country: "Guernsey", shortAbbreviation: "GG", longAbbreviation: "GGY", callCode: "+1481"),
                CountryInfo(country: "Guinea", shortAbbreviation: "GN", longAbbreviation: "GIN", callCode: "+225"),
                CountryInfo(country: "Guinea-Bissau", shortAbbreviation: "GW", longAbbreviation: "GNB", callCode: "+245"),
                CountryInfo(country: "Guyana", shortAbbreviation: "GY", longAbbreviation: "GUY", callCode: "+592"),
                CountryInfo(country: "Haiti", shortAbbreviation: "HT", longAbbreviation: "HTI", callCode: "+509"),
                CountryInfo(country: "Heard Island and McDonald Islands", shortAbbreviation: "HM", longAbbreviation: "HMD", callCode: "+61"),
                CountryInfo(country: "Holy See (Vatican City State)", shortAbbreviation: "VA", longAbbreviation: "VAT", callCode: "+379"),
                CountryInfo(country: "Honduras", shortAbbreviation: "HN", longAbbreviation: "HND", callCode: "+504"),
                CountryInfo(country: "Hong Kong", shortAbbreviation: "HK", longAbbreviation: "HKG", callCode: "+852"),
                CountryInfo(country: "Hungary", shortAbbreviation: "HU", longAbbreviation: "HUN", callCode: "+36"),
                CountryInfo(country: "Iceland", shortAbbreviation: "IS", longAbbreviation: "ISL", callCode: "+354"),
                CountryInfo(country: "India", shortAbbreviation: "IN", longAbbreviation: "IND", callCode: "+91"),
                CountryInfo(country: "Indonesia", shortAbbreviation: "ID", longAbbreviation: "IDN", callCode: "+62"),
                CountryInfo(country: "Iran, Islamic Republic of", shortAbbreviation: "IR", longAbbreviation: "IRN", callCode: "+98"),
                CountryInfo(country: "Iraq", shortAbbreviation: "IQ", longAbbreviation: "IRQ", callCode: "+964"),
                CountryInfo(country: "Ireland", shortAbbreviation: "IE", longAbbreviation: "IRL", callCode: "+353"),
                CountryInfo(country: "Isle of Man", shortAbbreviation: "IM", longAbbreviation: "IMN", callCode: "+44"),
                CountryInfo(country: "Israel", shortAbbreviation: "IL", longAbbreviation: "ISR", callCode: "+972"),
                CountryInfo(country: "Italy", shortAbbreviation: "IT", longAbbreviation: "ITA", callCode: "+39"),
                CountryInfo(country: "Jamaica", shortAbbreviation: "JM", longAbbreviation: "JAM", callCode: "+876"),
                CountryInfo(country: "Japan", shortAbbreviation: "JP", longAbbreviation: "JPN", callCode: "+81"),
                CountryInfo(country: "Jersey", shortAbbreviation: "JE", longAbbreviation: "JEY", callCode: "+44"),
                CountryInfo(country: "Jordan", shortAbbreviation: "JO", longAbbreviation: "JOR", callCode: "+962"),
                CountryInfo(country: "Kazakhstan", shortAbbreviation: "KZ", longAbbreviation: "KAZ", callCode: "+7"),
                CountryInfo(country: "Kenya", shortAbbreviation: "KE", longAbbreviation: "KEN", callCode: "+254"),
                CountryInfo(country: "Kiribati", shortAbbreviation: "KI", longAbbreviation: "KIR", callCode: "+686"),
                CountryInfo(country: "Korea, Democratic People's Republic of", shortAbbreviation: "KP", longAbbreviation: "PRK", callCode: "+850"),
                CountryInfo(country: "Korea, Republic of", shortAbbreviation: "KR", longAbbreviation: "KOR", callCode: "+82"),
                CountryInfo(country: "Kuwait", shortAbbreviation: "KW", longAbbreviation: "KWT", callCode: "+965"),
                CountryInfo(country: "Kyrgyzstan", shortAbbreviation: "KG", longAbbreviation: "KGZ", callCode: "+996"),
                CountryInfo(country: "Lao People's Democratic Republic", shortAbbreviation: "LA", longAbbreviation: "LAO", callCode: "+856"),
                CountryInfo(country: "Latvia", shortAbbreviation: "LV", longAbbreviation: "LVA", callCode: "+371"),
                CountryInfo(country: "Lebanon", shortAbbreviation: "LB", longAbbreviation: "LBN", callCode: "+961"),
                CountryInfo(country: "Lesotho", shortAbbreviation: "LS", longAbbreviation: "LSO", callCode: "+266"),
                CountryInfo(country: "Liberia", shortAbbreviation: "LR", longAbbreviation: "LBR", callCode: "+231"),
                CountryInfo(country: "Libya", shortAbbreviation: "LY", longAbbreviation: "LBY", callCode: "+218"),
                CountryInfo(country: "Liechtenstein", shortAbbreviation: "LI", longAbbreviation: "LIE", callCode: "+423"),
                CountryInfo(country: "Lithuania", shortAbbreviation: "LT", longAbbreviation: "LTU", callCode: "+370"),
                CountryInfo(country: "Luxembourg", shortAbbreviation: "LU", longAbbreviation: "LUX", callCode: "+352"),
                CountryInfo(country: "Macao", shortAbbreviation: "MO", longAbbreviation: "MAC", callCode: "+853"),
                CountryInfo(country: "Macedonia, the former Yugoslav Republic of", shortAbbreviation: "MK", longAbbreviation: "MKD", callCode: "+389"),
                CountryInfo(country: "Madagascar", shortAbbreviation: "MG", longAbbreviation: "MDG", callCode: "+261"),
                CountryInfo(country: "Malawi", shortAbbreviation: "MW", longAbbreviation: "MWI", callCode: "+265"),
                CountryInfo(country: "Malaysia", shortAbbreviation: "MY", longAbbreviation: "MYS", callCode: "+60"),
                CountryInfo(country: "Maldives", shortAbbreviation: "MV", longAbbreviation: "MDV", callCode: "+960"),
                CountryInfo(country: "Mali", shortAbbreviation: "ML", longAbbreviation: "MLI", callCode: "+223"),
                CountryInfo(country: "Malta", shortAbbreviation: "MT", longAbbreviation: "MLT", callCode: "+356"),
                CountryInfo(country: "Marshall Islands", shortAbbreviation: "MH", longAbbreviation: "MHL", callCode: "+692"),
                CountryInfo(country: "Martinique", shortAbbreviation: "MQ", longAbbreviation: "MTQ", callCode: "+596"),
                CountryInfo(country: "Mauritania", shortAbbreviation: "MR", longAbbreviation: "MRT", callCode: "+222"),
                CountryInfo(country: "Mauritius", shortAbbreviation: "MU", longAbbreviation: "MUS", callCode: "+230"),
                CountryInfo(country: "Mayotte", shortAbbreviation: "YT", longAbbreviation: "MYT", callCode: "+262"),
                CountryInfo(country: "Mexico", shortAbbreviation: "MX", longAbbreviation: "MEX", callCode: "+52"),
                CountryInfo(country: "Micronesia, Federated States of", shortAbbreviation: "FM", longAbbreviation: "FSM", callCode: "+691"),
                CountryInfo(country: "Moldova, Republic of", shortAbbreviation: "MD", longAbbreviation: "MDA", callCode: "+373"),
                CountryInfo(country: "Monaco", shortAbbreviation: "MC", longAbbreviation: "MCO", callCode: "+355"),
                CountryInfo(country: "Mongolia", shortAbbreviation: "MN", longAbbreviation: "MNG", callCode: "+976"),
                CountryInfo(country: "Montenegro", shortAbbreviation: "ME", longAbbreviation: "MNE", callCode: "+382"),
                CountryInfo(country: "Montserrat", shortAbbreviation: "MS", longAbbreviation: "MSR", callCode: "+664"),
                CountryInfo(country: "Morocco", shortAbbreviation: "MA", longAbbreviation: "MAR", callCode: "+212"),
                CountryInfo(country: "Mozambique", shortAbbreviation: "MZ", longAbbreviation: "MOZ", callCode: "+258"),
                CountryInfo(country: "Myanmar", shortAbbreviation: "MM", longAbbreviation: "MMR", callCode: "+95"),
                CountryInfo(country: "Namibia", shortAbbreviation: "NA", longAbbreviation: "NAM", callCode: "+264"),
                CountryInfo(country: "Nauru", shortAbbreviation: "NR", longAbbreviation: "NRU", callCode: "+674"),
                CountryInfo(country: "Nepal", shortAbbreviation: "NP", longAbbreviation: "NPL", callCode: "+977"),
                CountryInfo(country: "Netherlands", shortAbbreviation: "NL", longAbbreviation: "NLD", callCode: "+31"),
                CountryInfo(country: "New Caledonia", shortAbbreviation: "NC", longAbbreviation: "NCL", callCode: "+687"),
                CountryInfo(country: "New Zealand", shortAbbreviation: "NZ", longAbbreviation: "NZL", callCode: "+64"),
                CountryInfo(country: "Nicaragua", shortAbbreviation: "NI", longAbbreviation: "NIC", callCode: "+505"),
                CountryInfo(country: "Niger", shortAbbreviation: "NE", longAbbreviation: "NER", callCode: "+277"),
                CountryInfo(country: "Nigeria", shortAbbreviation: "NG", longAbbreviation: "NGA", callCode: "+234"),
                CountryInfo(country: "Niue", shortAbbreviation: "NU", longAbbreviation: "NIU", callCode: "+683"),
                CountryInfo(country: "Norfolk Island", shortAbbreviation: "NF", longAbbreviation: "NFK", callCode: "+672"),
                CountryInfo(country: "Northern Mariana Islands", shortAbbreviation: "MP", longAbbreviation: "MNP", callCode: "+670"),
                CountryInfo(country: "Norway", shortAbbreviation: "NO", longAbbreviation: "NOR", callCode: "+47"),
                CountryInfo(country: "Oman", shortAbbreviation: "OM", longAbbreviation: "OMN", callCode: "+968"),
                CountryInfo(country: "Pakistan", shortAbbreviation: "PK", longAbbreviation: "PAK", callCode: "+92"),
                CountryInfo(country: "Palau", shortAbbreviation: "PW", longAbbreviation: "PLW", callCode: "+680"),
                CountryInfo(country: "Palestine, State of", shortAbbreviation: "PS", longAbbreviation: "PSE", callCode: "+970"),
                CountryInfo(country: "Panama", shortAbbreviation: "PA", longAbbreviation: "PAN", callCode: "+507"),
                CountryInfo(country: "Papua New Guinea", shortAbbreviation: "PG", longAbbreviation: "PNG", callCode: "+675"),
                CountryInfo(country: "Paraguay", shortAbbreviation: "PY", longAbbreviation: "PRY", callCode: "+595"),
                CountryInfo(country: "Peru", shortAbbreviation: "PE", longAbbreviation: "PER", callCode: "+51"),
                CountryInfo(country: "Philippines", shortAbbreviation: "PH", longAbbreviation: "PHL", callCode: "+63"),
                CountryInfo(country: "Pitcairn", shortAbbreviation: "PN", longAbbreviation: "PCN", callCode: "+872"),
                CountryInfo(country: "Poland", shortAbbreviation: "PL", longAbbreviation: "POL", callCode: "+48"),
                CountryInfo(country: "Portugal", shortAbbreviation: "PT", longAbbreviation: "PRT", callCode: "+351"),
                CountryInfo(country: "Puerto Rico", shortAbbreviation: "PR", longAbbreviation: "PRI", callCode: "+787"),
                CountryInfo(country: "Qatar", shortAbbreviation: "QA", longAbbreviation: "QAT", callCode: "+974"),
                CountryInfo(country: "Réunion", shortAbbreviation: "RE", longAbbreviation: "REU", callCode: "+262"),
                CountryInfo(country: "Romania", shortAbbreviation: "RO", longAbbreviation: "ROU", callCode: "+40"),
                CountryInfo(country: "Russian Federation", shortAbbreviation: "RU", longAbbreviation: "RUS", callCode: "+7"),
                CountryInfo(country: "Rwanda", shortAbbreviation: "RW", longAbbreviation: "RWA", callCode: "+250"),
                CountryInfo(country: "Saint Barthélemy", shortAbbreviation: "BL", longAbbreviation: "BLM", callCode: "+590"),
                CountryInfo(country: "Saint Helena, Ascension and Tristan da Cunha", shortAbbreviation: "SH", longAbbreviation: "SHN", callCode: "+290"),
                CountryInfo(country: "Saint Kitts and Nevis", shortAbbreviation: "KN", longAbbreviation: "KNA", callCode: "+869"),
                CountryInfo(country: "Saint Lucia", shortAbbreviation: "LC", longAbbreviation: "LCA", callCode: "+758"),
                CountryInfo(country: "Saint Martin (French part)", shortAbbreviation: "MF", longAbbreviation: "MAF", callCode: "+590"),
                CountryInfo(country: "Saint Pierre and Miquelon", shortAbbreviation: "PM", longAbbreviation: "SPM", callCode: "+508"),
                CountryInfo(country: "Saint Vincent and the Grenadines", shortAbbreviation: "VC", longAbbreviation: "VCT", callCode: "+784"),
                CountryInfo(country: "Samoa", shortAbbreviation: "WS", longAbbreviation: "WSM", callCode: "+685"),
                CountryInfo(country: "San Marino", shortAbbreviation: "SM", longAbbreviation: "SMR", callCode: "+378"),
                CountryInfo(country: "Sao Tome and Principe", shortAbbreviation: "ST", longAbbreviation: "STP", callCode: "+239"),
                CountryInfo(country: "Saudi Arabia", shortAbbreviation: "SA", longAbbreviation: "SAU", callCode: "+966"),
                CountryInfo(country: "Senegal", shortAbbreviation: "SN", longAbbreviation: "SEN", callCode: "+221"),
                CountryInfo(country: "Serbia", shortAbbreviation: "RS", longAbbreviation: "SRB", callCode: "+381"),
                CountryInfo(country: "Seychelles", shortAbbreviation: "SC", longAbbreviation: "SYC", callCode: "+248"),
                CountryInfo(country: "Sierra Leone", shortAbbreviation: "SL", longAbbreviation: "SLE", callCode: "+232"),
                CountryInfo(country: "Singapore", shortAbbreviation: "SG", longAbbreviation: "SGP", callCode: "+65"),
                CountryInfo(country: "Sint Maarten (Dutch part)", shortAbbreviation: "SX", longAbbreviation: "SXM", callCode: "+599"),
                CountryInfo(country: "Slovakia", shortAbbreviation: "SK", longAbbreviation: "SVK", callCode: "+421"),
                CountryInfo(country: "Slovenia", shortAbbreviation: "SI", longAbbreviation: "SVN", callCode: "+386"),
                CountryInfo(country: "Solomon Islands", shortAbbreviation: "SB", longAbbreviation: "SLB", callCode: "+677"),
                CountryInfo(country: "Somalia", shortAbbreviation: "SO", longAbbreviation: "SOM", callCode: "+252"),
                CountryInfo(country: "South Africa", shortAbbreviation: "ZA", longAbbreviation: "ZAF", callCode: "+27"),
                CountryInfo(country: "South Georgia and the South Sandwich Islands", shortAbbreviation: "GS", longAbbreviation: "SGS", callCode: "+500"),
                CountryInfo(country: "South Sudan", shortAbbreviation: "SS", longAbbreviation: "SSD", callCode: "+211"),
                CountryInfo(country: "Spain", shortAbbreviation: "ES", longAbbreviation: "ESP", callCode: "+34"),
                CountryInfo(country: "Sri Lanka", shortAbbreviation: "LK", longAbbreviation: "LKA", callCode: "+94"),
                CountryInfo(country: "Sudan", shortAbbreviation: "SD", longAbbreviation: "SDN", callCode: "+249"),
                CountryInfo(country: "Suriname", shortAbbreviation: "SR", longAbbreviation: "SUR", callCode: "+597"),
                CountryInfo(country: "Svalbard and Jan Mayen", shortAbbreviation: "SJ", longAbbreviation: "SJM", callCode: "+47"),
                CountryInfo(country: "Swaziland", shortAbbreviation: "SZ", longAbbreviation: "SWZ", callCode: "+268"),
                CountryInfo(country: "Sweden", shortAbbreviation: "SE", longAbbreviation: "SWE", callCode: "+46"),
                CountryInfo(country: "Switzerland", shortAbbreviation: "CH", longAbbreviation: "CHE", callCode: "+41"),
                CountryInfo(country: "Syrian Arab Republic", shortAbbreviation: "SY", longAbbreviation: "SYR", callCode: "+963"),
                CountryInfo(country: "Taiwan, Province of China", shortAbbreviation: "TW", longAbbreviation: "TWN", callCode: "+886"),
                CountryInfo(country: "Tajikistan", shortAbbreviation: "TJ", longAbbreviation: "TJK", callCode: "+992"),
                CountryInfo(country: "Tanzania, United Republic of", shortAbbreviation: "TZ", longAbbreviation: "TZA", callCode: "+255"),
                CountryInfo(country: "Thailand", shortAbbreviation: "TH", longAbbreviation: "THA", callCode: "+66"),
                CountryInfo(country: "Timor-Leste", shortAbbreviation: "TL", longAbbreviation: "TLS", callCode: "+670"),
                CountryInfo(country: "Togo", shortAbbreviation: "TG", longAbbreviation: "TGO", callCode: "+228"),
                CountryInfo(country: "Tokelau", shortAbbreviation: "TK", longAbbreviation: "TKL", callCode: "+690"),
                CountryInfo(country: "Tonga", shortAbbreviation: "TO", longAbbreviation: "TON", callCode: "+676"),
                CountryInfo(country: "Trinidad and Tobago", shortAbbreviation: "TT", longAbbreviation: "TTO", callCode: "+868"),
                CountryInfo(country: "Tunisia", shortAbbreviation: "TN", longAbbreviation: "TUN", callCode: "+216"),
                CountryInfo(country: "Turkey", shortAbbreviation: "TR", longAbbreviation: "TUR", callCode: "+90"),
                CountryInfo(country: "Turkmenistan", shortAbbreviation: "TM", longAbbreviation: "TKM", callCode: "+993"),
                CountryInfo(country: "Turks and Caicos Islands", shortAbbreviation: "TC", longAbbreviation: "TCA", callCode: "+649"),
                CountryInfo(country: "Tuvalu", shortAbbreviation: "TV", longAbbreviation: "TUV", callCode: "+688"),
                CountryInfo(country: "Uganda", shortAbbreviation: "UG", longAbbreviation: "UGA", callCode: "+256"),
                CountryInfo(country: "Ukraine", shortAbbreviation: "UA", longAbbreviation: "UKR", callCode: "+380"),
                CountryInfo(country: "United Arab Emirates", shortAbbreviation: "AE", longAbbreviation: "ARE", callCode: "+971"),
                CountryInfo(country: "United Kingdom", shortAbbreviation: "GB", longAbbreviation: "GBR", callCode: "+44"),
                CountryInfo(country: "United States", shortAbbreviation: "US", longAbbreviation: "USA", callCode: "+1"),
                CountryInfo(country: "United States Minor Outlying Islands", shortAbbreviation: "UM", longAbbreviation: "UMI", callCode: "+1"),
                CountryInfo(country: "Uruguay", shortAbbreviation: "UY", longAbbreviation: "URY", callCode: "+598"),
                CountryInfo(country: "Uzbekistan", shortAbbreviation: "UZ", longAbbreviation: "UZB", callCode: "+998"),
                CountryInfo(country: "Vanuatu", shortAbbreviation: "VU", longAbbreviation: "VUT", callCode: "+678"),
                CountryInfo(country: "Venezuela, Bolivarian Republic of", shortAbbreviation: "VE", longAbbreviation: "VEN", callCode: "+58"),
                CountryInfo(country: "Vietnam", shortAbbreviation: "VN", longAbbreviation: "VNM", callCode: "+84"),
                CountryInfo(country: "Virgin Islands, British", shortAbbreviation: "VG", longAbbreviation: "VGB", callCode: "+284"),
                CountryInfo(country: "Virgin Islands, U.S.", shortAbbreviation: "VI", longAbbreviation: "VIR", callCode: "+340"),
                CountryInfo(country: "Wallis and Futuna", shortAbbreviation: "WF", longAbbreviation: "WLF", callCode: "+681"),
                CountryInfo(country: "Western Sahara", shortAbbreviation: "EH", longAbbreviation: "ESH", callCode: "+212"),
                CountryInfo(country: "Yemen", shortAbbreviation: "YE", longAbbreviation: "YEM", callCode: "+967"),
                CountryInfo(country: "Zambia", shortAbbreviation: "ZM", longAbbreviation: "ZMB", callCode: "+260"),
                CountryInfo(country: "Zimbabwe", shortAbbreviation: "ZW", longAbbreviation: "ZWE", callCode: "+263")]
        }
    }
    
}
